/**
 * The seeded administrators for a store.
 *
 * Admins are **seeded, never self-registered** (`IDENTITY.md`). This file is the whole
 * list: `pnpm seed:admins` reads it, mints or updates each Auth user, and sets the `role`
 * custom claim. There is no invite flow and no admin signup, so an operator exists exactly
 * because they appear here.
 *
 * The identifier is an email or a mobile number in any spelling — it is normalised the same
 * way a customer's is, through `@romp/core`, so an admin signs in through the identical
 * alias mechanism. `role` is `owner` (may issue refunds and change settings) or `staff`
 * (backoffice reads and order handling); it maps directly to the `@romp/data` `Role` the
 * API's role guard reads from the verified claim.
 *
 * **This file is committed, so it must not contain passwords.** Initial passwords are
 * generated by the seed script and printed once, out of band, for the operator to change on
 * first sign-in. The list here is identity and authorisation only.
 *
 * Per store, this is overridden by `stores/<id>/admins.config.ts` when present; the values
 * below are the defaults used when a store ships none.
 */
export interface AdminSeed {
  /** Email or mobile number, unnormalised — normalised by the seed script. */
  readonly identifier: string;
  readonly displayName: string;
  readonly role: 'owner' | 'staff';
}

export const admins: readonly AdminSeed[] = [
  {
    identifier: 'owner@example.com',
    displayName: 'Store Owner',
    role: 'owner',
  },
];
