/**
 * Emits the generated white-label artefacts for the active store.
 *
 *   pnpm store:tokens                 # active store, from STORE_ID or `romp`
 *   STORE_ID=_template pnpm store:tokens
 *
 * Writes into `packages/store-config/generated/` and into each app's
 * `src/generated/`. Both are gitignored — they are build outputs, and committing them
 * would create a second source of truth that can disagree with the config.
 *
 * **This is where a bad config is caught.** Validation runs here, at build time, with
 * the exact path of whatever is wrong. Validating inside a React component instead
 * would surface the same error as a half-branded page in production, at whatever
 * moment that route was first requested.
 *
 * Run through `jiti` because the store config is TypeScript and Node 20 — our floor —
 * cannot load it.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadStoreConfig, resolveStoreId, storeDirectory } from '../src/loader';
import type { StoreConfig } from '../src/schema';
import { publicRuntimeConfig, renderFontsModule, renderThemeCss } from '../src/tokens';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(packageRoot, '..', '..');

/**
 * Apps that should receive the per-app generated artefacts (theme CSS, the `next/font`
 * module, the public config).
 *
 * Opt-in via `"romp": { "storeArtefacts": true }` in the app's package.json, not "every
 * app with a package.json" — the API is a Fastify service with no `next/font` and no CSS
 * graph, so emitting a `fonts.ts` that imports `next/font/google` into it breaks its
 * typecheck. A rendering app declares that it wants them; a service does not.
 */
function appDirectories(): readonly string[] {
  const appsRoot = join(repoRoot, 'apps');
  if (!existsSync(appsRoot)) return [];

  return readdirSync(appsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(appsRoot, entry.name))
    .filter((directory) => wantsStoreArtefacts(directory));
}

/** Whether an app opts into the per-app generated artefacts. */
function wantsStoreArtefacts(directory: string): boolean {
  const manifestPath = join(directory, 'package.json');
  if (!existsSync(manifestPath)) return false;
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
    romp?: { storeArtefacts?: boolean };
  };
  return manifest.romp?.storeArtefacts === true;
}

function write(directory: string, files: readonly [string, string][]): string[] {
  mkdirSync(directory, { recursive: true });
  for (const [name, contents] of files) {
    writeFileSync(join(directory, name), contents, 'utf8');
  }
  return files.map(([name]) => join(relative(repoRoot, directory), name));
}

function packageArtefacts(storeId: string, config: StoreConfig): readonly [string, string][] {
  return [
    ['theme.css', renderThemeCss(config)],
    // Safe for the browser bundle: no warehouse addresses or PIN prefixes.
    ['public-config.json', `${JSON.stringify(publicRuntimeConfig(config), null, 2)}\n`],
    // The full config, for server-side consumers that legitimately need warehouses.
    ['store-config.json', `${JSON.stringify(config, null, 2)}\n`],
    [
      'active-store.ts',
      [
        '// Generated by @romp/store-config. Do not edit.',
        '// Run `pnpm store:tokens` to regenerate.',
        `export const ACTIVE_STORE_ID = ${JSON.stringify(storeId)} as const;`,
        '',
      ].join('\n'),
    ],
  ];
}

/**
 * Per-app artefacts.
 *
 * `theme.css` is copied rather than imported across the package boundary so each app's
 * CSS entry point can `@import './generated/theme.css'` with a relative path — which is
 * what Tailwind's `@theme` block needs in order to be part of the app's own CSS graph.
 */
function appArtefacts(config: StoreConfig): readonly [string, string][] {
  return [
    ['theme.css', renderThemeCss(config)],
    ['fonts.ts', renderFontsModule(config)],
    ['public-config.json', `${JSON.stringify(publicRuntimeConfig(config), null, 2)}\n`],
  ];
}

/**
 * Copies the store's artwork into an app's `public/brand/`.
 *
 * Served from `public/` rather than imported, because these are referenced by path from
 * config (`assets/logo-dark.svg`) and by the web manifest and favicon links, which need
 * stable URLs. Copying is what makes a logo swap part of switching `STORE_ID` rather than
 * a code change.
 *
 * **File-level sync rather than remove-then-copy the directory**, because the generator
 * writes artefacts for every `storeArtefacts` app in one run and turbo can invoke it from
 * more than one entry point at once (a package's `tokens` task and an app's `prebuild`
 * hook). A directory-level `rmSync` then `cpSync` races two concurrent runs into an
 * `ENOTEMPTY` — one run copying into a directory the other is mid-rebuild of. Copying each
 * file in place (overwrite) and pruning only files the source no longer has is idempotent
 * under concurrency: two runs write identical bytes to identical paths, last write wins, and
 * the directory is never removed out from under a sibling. A renamed asset still does not
 * linger, because the prune step removes anything not in the source.
 */
function copyBrandAssets(storeId: string, appDirectory: string): string[] {
  const source = join(storeDirectory(storeId), 'assets');
  const target = join(appDirectory, 'public', 'brand');

  mkdirSync(target, { recursive: true });

  // A byte-for-byte copy via read+write rather than `cpSync`. `cpSync` performs an
  // `equivalent(source, target)` "same file?" check internally, and that check throws when a
  // concurrent run has the target mid-flight — the exact race two builds hit. `readFileSync`
  // then `writeFileSync` has no such check: two runs write identical bytes to the same path,
  // last write wins. Brand assets are small SVG/PNG, so reading them whole is cheap.
  const sourceNames = new Set(readdirSync(source));
  for (const name of sourceNames) {
    writeFileSync(join(target, name), readFileSync(join(source, name)));
  }

  // Prune stale files the source no longer carries, so a renamed asset is not served forever.
  for (const name of readdirSync(target)) {
    if (!sourceNames.has(name)) {
      rmSync(join(target, name), { recursive: true, force: true });
    }
  }

  return [...sourceNames].map((name) => join(relative(repoRoot, target), name));
}

async function main(): Promise<void> {
  // Scaffolds are allowed here so `STORE_ID=_template pnpm store:tokens` can be used to
  // check the template still emits valid artefacts.
  const storeId = resolveStoreId(process.env.STORE_ID, { allowScaffold: true });
  const config = await loadStoreConfig(storeId, { allowScaffold: true });

  const written = [
    ...write(join(packageRoot, 'generated'), packageArtefacts(storeId, config)),
    ...appDirectories().flatMap((directory) => [
      ...write(join(directory, 'src', 'generated'), appArtefacts(config)),
      ...copyBrandAssets(storeId, directory),
    ]),
  ];

  process.stdout.write(
    `Generated ${String(written.length)} artefacts for store "${storeId}":\n${written
      .map((path) => `  ${path}\n`)
      .join('')}`,
  );
}

try {
  await main();
} catch (error) {
  // A config error is a build failure with an actionable message, not a stack trace.
  process.stderr.write(`\n${error instanceof Error ? error.message : String(error)}\n\n`);
  process.exit(1);
}
